/* ============================================================================
   sia.js — GENERADO AUTOMÁTICAMENTE, no editar a mano.
   Fichas derivadas del Catálogo de asignaturas del SIA (carreras/<slug>/oferta.js), consultado
   el 2026-08-18. Traen créditos, tipología y descripción; no temario ni horas.
   Cuando «Contenido de asignaturas» vuelva a responder, sustituir con:
   node herramientas/sia.js enriquecer
   Regenerar con: node herramientas/catalogo-sia.js fichas
   ========================================================================== */

const SIA_CONSULTADO = '2026-08-18';

/* "código|nombre de la malla" -> ficha */
const SIA = {
 "1000041|Química básica": {
  "cod": "1000041",
  "nombre": "Química básica",
  "vigente": true,
  "unidad": null,
  "creditos": 3,
  "semanas": null,
  "horas": null,
  "validable": null,
  "asistencia": null,
  "libreEleccion": null,
  "descripcion": "METODOLOGÍA: Esta asignatura se desarrollará mediante exposiciones orales por parte del profesor. Se propondrán actividades de reforzamiento y repaso (talleres y lecturas complementarias).\nOBJETIVOS:\n1. Preparar al estudiante para la interpretación de fenómenos involucrados en diferentes procesos químicos.\n2. Promover el aprendizaje y comprensión del lenguaje básico de la Química básica y orgánica como herramienta indispensable para su desarrollo profesional, su trabajo interdisciplinario y para que entienda la vida cotidiana desde la óptica de los procesos químicos.\n3. Aumentar el interés en los estudiantes por la comprensión del comportamiento de la materia a nivel atómico y molecular para que lo pueda relacionar con procesos observables a nivel macroscópico.\n4. Potencializar competencias interpretativas, propositivas y argumentativas fundamentadas en el lenguaje químico.\n5. Fomentar la integración de los conceptos de materia y energía de creciente relevancia en el presente siglo, en todas las actividades del quehacer cotidiano.\n6. Desarrollar habilidades y destrezas para la resolución de ejercicios y problemas que requieran de conocimientos de Química.\n7. Fomentar el aprendizaje de conceptos básicos de estructura molecular, nomenclatura y propiedades físicas y químicas de algunos grupos funcionales orgánicos.\n8. Promover en el estudiante el uso responsable de los conocimientos de química en su entorno, especialmente con el cuidado del medio ambiente.",
  "contenido": null,
  "tipologia": "FUND. OBLIGATORIA",
  "via": "catalogo-sia"
 },
 "2017048|Bioética y bienestar en salud animal": {
  "cod": "2017048",
  "nombre": "Bioética y bienestar en salud animal",
  "vigente": true,
  "unidad": null,
  "creditos": 3,
  "semanas": null,
  "horas": null,
  "validable": null,
  "asistencia": null,
  "libreEleccion": null,
  "descripcion": "JUSTIFICACIÓN\nLa Facultad de Medicina Veterinaria y de Zootecnia, preocupada por velar por el bienestar animal, se propone hacer un acercamiento entre los estudiantes, la normatividad vigente, y las actividades que emplean animales vivos en docencia, producción, investigación y extensión.\n\nEn consecuencia, se plantea la creación de la cátedra de bioética y bienestar animal, acorde a la legislación nacional: Resolución 008430 de 1993, Ley 84 de 1989 y Ley 576 del 2000.\n\nOBJETIVOS\n\nGeneral\n\nIncorporar los conceptos de bioética y bienestar en el manejo y tenencia de los animales como una disciplina en el currículo de la Facultad de Medicina Veterinaria y de Zootecnia de la Universidad Nacional de Colombia.\n\nEspecíficos\n\nDesarrollar el entendimiento del bienestar animal en relación al balance emocional y fisiológico.\nGenerar la capacidad de integrar las implicaciones legales, éticas y de bienestar animal para hacer análisis crítico desde cada perspectiva de participación de los animales en el desarrollo académico científico.\nEstimular un pensamiento crítico de los temas de bienestar animal que serán desarrollados a través del curso.\nFamiliarizar a la comunidad académica con la normatividad vigente sobre los derechos de los animales, y capacitar al personal vinculado al manejo y cuidado de los animales.\n\"",
  "contenido": null,
  "tipologia": "FUND. OBLIGATORIA",
  "via": "catalogo-sia"
 },
 "2017066|Introducción a las ciencias veterinarias": {
  "cod": "2017066",
  "nombre": "Introducción a las ciencias veterinarias",
  "vigente": true,
  "unidad": null,
  "creditos": 2,
  "semanas": null,
  "horas": null,
  "validable": null,
  "asistencia": null,
  "libreEleccion": null,
  "descripcion": "El componente práctico de manejo animal, pretende acercar al estudiante a conceptos y habilidades necesarias y obligatorias en el quehacer del Medico Veterinario.",
  "contenido": null,
  "tipologia": "FUND. OBLIGATORIA",
  "via": "catalogo-sia"
 },
 "1000044|Inglés I": {
  "cod": "1000044",
  "nombre": "Inglés I- Semestral",
  "vigente": true,
  "unidad": null,
  "creditos": 3,
  "semanas": null,
  "horas": null,
  "validable": null,
  "asistencia": null,
  "libreEleccion": null,
  "descripcion": "Se espera que los estudiantes al término de este primer nivel de inglés, puedan comprender textos expositivos cortos relacionados con temáticas de tipo académico y que además, puedan expresar de manera oral y escrita información de tipo personal. Con base en un listado de descriptores predeterminados, el profesor selecciona el material que puede utilizar y ayuda al estudiante a partir del uso de estrategias de aprendizaje, para que poco a poco sea él o ella quien tenga el criterio para saber qué información le sirve, por qué y cómo usarla.",
  "contenido": null,
  "tipologia": "NIVELACIÓN",
  "via": "catalogo-sia"
 },
 "2017046|Anatomía comparada": {
  "cod": "2017046",
  "nombre": "Anatomía comparada",
  "vigente": true,
  "unidad": null,
  "creditos": 5,
  "semanas": null,
  "horas": null,
  "validable": null,
  "asistencia": null,
  "libreEleccion": null,
  "descripcion": "La asignatura de Anatomía proveerá al estudiante un conocimiento claro sobre la forma, estructura, función y relaciones recíprocas que establecen los órganos en los animales domésticos, con un enfoque aplicado y de manera comparada. Su estudio permitirá sentar las bases de la comprensión de la estructura y función de los diferentes componentes anatómicos.\n\nLa asignatura se desarrollará mediante un componente teórico (clases magistrales) y su complemento mediante clases prácticas (anfiteatro). Lecturas obligatorias serán discutidas y evaluadas durante el curso.\n\nSe desarrollaran competencias transversales, específicas y disciplinares",
  "contenido": null,
  "tipologia": "FUND. OBLIGATORIA",
  "via": "catalogo-sia"
 },
 "2017063|Histología y embriología": {
  "cod": "2017063",
  "nombre": "Histología y embriología",
  "vigente": true,
  "unidad": null,
  "creditos": 4,
  "semanas": null,
  "horas": null,
  "validable": null,
  "asistencia": null,
  "libreEleccion": null,
  "descripcion": "El conocimiento de la estructura de los animales domésticos es fundamental para la comprensión de la fisiología y una base imprescindible para conocer as alteraciones morfológicas que pueden verse con el microscopio óptico.\n\nLa histología, en el sentido estricto, es el estudio de los tejidos básicos constituyentes ellos, en asociación armónica, de los órganos, que a su vez forman también de una histología de los órganos que incluye su morfología como se observa en los cortes teñidos bajo el microscopio de luz o electrónico de transmisión.",
  "contenido": null,
  "tipologia": "FUND. OBLIGATORIA",
  "via": "catalogo-sia"
 },
 "1000042|Bioquímica básica": {
  "cod": "1000042",
  "nombre": "Bioquímica básica",
  "vigente": true,
  "unidad": null,
  "creditos": 3,
  "semanas": null,
  "horas": null,
  "validable": null,
  "asistencia": null,
  "libreEleccion": null,
  "descripcion": "METODOLOGIA:\nExposición de temas por parte del profesor\nEjercicios y talleres de aplicación\nLecturas complementarias\n\nOBJETIVOS:\n1. Que el estudiante conozca las estructuras de los principales compuestos de importancia biológica.\n2. Que el estudiante com",
  "contenido": null,
  "tipologia": "FUND. OBLIGATORIA",
  "via": "catalogo-sia"
 },
 "2017049|Biofísica": {
  "cod": "2017049",
  "nombre": "Biofísica",
  "vigente": true,
  "unidad": null,
  "creditos": 2,
  "semanas": null,
  "horas": null,
  "validable": null,
  "asistencia": null,
  "libreEleccion": null,
  "descripcion": "El funcionamiento de los sistemas y órganos de los seres vivos tiene una sólida base en los principios y leyes de la física. Para una profesión como la Medicina Veterinaria se requiere que los fundamentos físicos tengan una integración real con los sistemas de órganos de los animales que representan un interés profesional.\n\nSin embargo, en la actualidad la biofísica ha evolucionado a un área relativamente bien definida que tiene poco que ver con la medicina, por lo menos manera directa, ya que se ha encargado de la física de las grandes biomoléculas, virus, etc. Pero durante su desarrollo incluía como una subespecialidad a la biofísica médica, en donde se busca: 1) comprender los principios de la física aplicados a las funciones corporales, y 2) comprender los principios físicos de los instrumentos usados en el diagnóstico médico. Por este motivo, el presente curso se enfocará en la biofísica médica.",
  "contenido": null,
  "tipologia": "FUND. OBLIGATORIA",
  "via": "catalogo-sia"
 },
 "1000012|Bioestadística fundamental": {
  "cod": "1000012",
  "nombre": "Bioestadística fundamental",
  "vigente": true,
  "unidad": null,
  "creditos": 3,
  "semanas": null,
  "horas": null,
  "validable": null,
  "asistencia": null,
  "libreEleccion": null,
  "descripcion": null,
  "contenido": null,
  "tipologia": "FUND. OBLIGATORIA",
  "via": "catalogo-sia"
 },
 "1000045|Inglés II": {
  "cod": "1000045",
  "nombre": "Inglés II - Semestral",
  "vigente": true,
  "unidad": null,
  "creditos": 3,
  "semanas": null,
  "horas": null,
  "validable": null,
  "asistencia": null,
  "libreEleccion": null,
  "descripcion": "Se espera que los estudiantes, al término del segundo nivel, puedan comprender textos expositivos y narrativos relacionados con temáticas de tipo académico y de cultura general. Se espera que en términos de comprensión escrita, el estudiante pueda identificar relaciones de temporalidad y secuencia, de contraste y de causa y efecto. Además se espera que puedan expresar de manera oral y escrita información relacionada con la descripción detallada de lugares, de estados de salud, eventos del pasado y planes. A partir de un listado de descriptores predeterminados, el profesor selecciona el material que puede utilizar y ayuda al estudiante, a través del uso de estrategias de aprendizaje, para que poco a poco sea él o ella quien tenga el criterio para saber qué le sirve, por qué y cómo usarlo. Se cuenta con un Centro de Recursos que le brinda tanto a profesores como estudiantes un buen número de recursos para la enseñanza y aprendizaje de la lengua.",
  "contenido": null,
  "tipologia": "NIVELACIÓN",
  "via": "catalogo-sia"
 },
 "2017061|Fisiología": {
  "cod": "2017061",
  "nombre": "Fisiología",
  "vigente": true,
  "unidad": null,
  "creditos": 5,
  "semanas": null,
  "horas": null,
  "validable": null,
  "asistencia": null,
  "libreEleccion": null,
  "descripcion": "OBJETIVOS:\n\n1. Preparar al estudiante para la comprensión de los principales eventos fisiológicos en las diferentes especies animales.\n2. Dar elementos para el abordaje de situaciones fisiopatológicas de interés en la práctica clínica.\n3. Dar a conocer las bases fisiológicas de los diferentes sistemas y sus potenciales aplicaciones en la producción animal.",
  "contenido": null,
  "tipologia": "FUND. OBLIGATORIA",
  "via": "catalogo-sia"
 },
 "2017050|Biología molecular avanzada": {
  "cod": "2017050",
  "nombre": "Biología molecular avanzada",
  "vigente": true,
  "unidad": null,
  "creditos": 2,
  "semanas": null,
  "horas": null,
  "validable": null,
  "asistencia": null,
  "libreEleccion": null,
  "descripcion": "INTRODUCCIÓN\nLA BIOLOGÍA MOLECULAR, HA TENIDO AVANCES EXTRAORDINARIOS EN LOS ÚLTIMOS 20 AÑOS. LAS TECNOLOGÍAS DE ADN RECOMBINANTE, PERMITIERON LA MANIPULACIÓN GENÉTICA (INGENIERÍA GENÉTICA) LO CUAL HA RESULTADO EN UNA REVOLUCIÓN BIOLÓGICA Y DIERON LAS BASES DE LA BIOTECNOLOGÍA Y DE MUCHAS INDUSTRIAS QUE DEPENDEN DE ÉSTA.\nLA BIOLOGÍA MOLECULAR HA JUGADO UN PAPEL SOBRESALIENTE EN EL ENTENDIMIENTO DE PROCESOS BIOLÓGICOS RELACIONADOS CON LOS ESTADOS FISIOLÓGICOS NORMALES Y LOS DE ENFERMEDAD A NIVEL INDIVIDUAL Y DE POBLACIONES. EL CONOCIMIENTO DE LA GENÉTICA MOLECULAR DE LOS DISTINTOS AGENTES ETIOLÓGICOS DE IMPORTANCIA EN LAS DIFERENTES ESPECIES ANIMALES, PROPORCIONA ELEMENTOS DE ANÁLISIS, QUE PERMITEN ESTABLECER SU EVOLUCIÓN GENÉTICA.\nEL EMPLEO DE LA BIOLOGÍA MOLECULAR A PERMITIDO UN MEJOR MANEJO DE LAS ENFERMEDADES DE LOS SERES VIVOS (HOMBRE, ESPECIES ANIMALES, PLANTAS) DESDE LA ÓPTICA DE LA PREVENCIÓN Y TRATAMIENTO DE LAS MISMAS, SIENDO EL USO DE TÉCNICAS MODERNAS DE BIOTECNOLOGÍA, DE UNA ALTA APLICACIÓN EN EL MEJORAMIENTO GENÉTICO DE ESPECIES PRODUCTIVAS (ANIMALES Y PLANTAS) MEDIANTE EL USO DE MARCADORES MOLECULARES QUE PERMITEN SELECCIONAR INDIVIDUOS SEGÚN SUS CARACTERÍSTICAS POSITIVAS DE PRODUCCIÓN O RESISTENCIA GENÉTICA A FACTORES ADVERSOS MEDIOAMBIENTALES.\n\nOBJETIVO GENERAL\nCAPACITAR A LOS ESTUDIANTES INTERESADOS EN EL TEMA, EN CONCEPTOS BÁSICOS, APLICACIONES PRÁCTICAS Y TENDENCIAS EN EL USO DE LA BIOLOGÍA MOLECULAR.\nOBJETIVOS ESPECÍFICOS\n\n- PROPORCIONAR A AQUELLOS ESTUDIANTES DE PREGRADO QUE ESTÉN INTERESADOS EN PROFUNDIZAR SOBRE LA APLICACIÓN DE LA BIOLOGÍA MOLECULAR, LAS HERRAMIENTAS QUE LE PERMITAN COMPLEMENTAR SU FORMACIÓN PROFESIONAL.\n\n- ESTABLECER LAS BASES PARA LA FORMACIÓN Y FORTALECIMIENTO DE LA MASA CRÍTICA EN ESTA ÁREA, QUE LE PERMITA AL ESTUDIANTE TENER VENTAJAS COMPARATIVAS, DENTRO DE SU FACULTAD. Y HACER PARTE DE EQUIPOS MULTIDISCIPLINARIOS DE INVESTIGACIÓN TANTO BÁSICA COMO APLICADA EN EL CAMPO DE LA BIOLOGÍA MOLECULAR.",
  "contenido": null,
  "tipologia": "FUND. OBLIGATORIA",
  "via": "catalogo-sia"
 },
 "2017065|Inmunología": {
  "cod": "2017065",
  "nombre": "Inmunología",
  "vigente": true,
  "unidad": null,
  "creditos": 2,
  "semanas": null,
  "horas": null,
  "validable": null,
  "asistencia": null,
  "libreEleccion": null,
  "descripcion": "La asignatura está diseñada para estudiantes de pregrado que cursan la carrera de Medicina\nVeterinaria, por tanto pretende suministrar los conceptos fundamentales de la inmunidad en los\nanimales con énfasis en especies domésticas y en forma comparada con el sistema inmune humano.\nEl curso es teórico práctico, contempla aspectos anatómicos, estrategias de defensa en las barreras\nfísicas, inmunidad innata e inmunidad específica. La función de homeostasis, los mecanismos\nhumorales así como las poblaciones celulares de respuesta inmune y las estrategias desarrolladas por\nel sistema para detectar, destruir y recordar, sustancias extrañas o propias que se encuentran\nalteradas. En cuanto a regulación de la respuesta se incluyen aspectos generales, como mecanismos\nde comunicación intercelular, las principales vías de regulación humoral y celular, importancia\nhormonal y tolerancia. Como aspectos aplicados del curso se dan a conocer las bases de la inmunidad\nmaterna, preñez, lactancia e inmunidad del neonato. Vacunas. Valoración de la respuesta inmune in\nVitro. Mecanismos de daño inmunológico y pruebas cutáneas con aplicación en diagnóstico.\nEl componente práctico contempla Células inmunes, pruebas serológicas de uso en diagnostico,\naglutinación, inmunodifusión, titilación sérica de anticuerpos, anticuerpos conjugados, fagocitosis,\nseparación de linfocitos sanguíneos y Valoración de inmunidad materna en terneros.",
  "contenido": null,
  "tipologia": "DISCIPLINAR OBLIGATORIA",
  "via": "catalogo-sia"
 },
 "1000046|Inglés III": {
  "cod": "1000046",
  "nombre": "Inglés III - Semestral",
  "vigente": true,
  "unidad": null,
  "creditos": 3,
  "semanas": null,
  "horas": null,
  "validable": null,
  "asistencia": null,
  "libreEleccion": null,
  "descripcion": "Se espera que los estudiantes, al término del tercer nivel, puedan leer y comprender textos auténticos de tipo académico y cultural, en los que, por ejemplo, se narren eventos o se describa un concepto a través del tiempo, se presente información de tipo periodístico, se explique el desarrollo de un fenómeno a través de una línea de realaciones de causa y efecto o se presente de manera sustentada un determinado punto de vista. Además se espera que puedan expresar de manera oral y escrita información relacionada con los conceptos trabajados a partir de la comprensión de lectura, que puedan sustentar su punto de vista y hacer reporte de la información queotraspersonaslestransmitan. Se cuenta con un Centro de Recursos que le brinda tanto a profesores como estudiantes un buen número de recursos para la enseñana y aprendizaje de la lengua.",
  "contenido": null,
  "tipologia": "NIVELACIÓN",
  "via": "catalogo-sia"
 },
 "2017062|Genética": {
  "cod": "2017062",
  "nombre": "Genética",
  "vigente": true,
  "unidad": null,
  "creditos": 3,
  "semanas": null,
  "horas": null,
  "validable": null,
  "asistencia": null,
  "libreEleccion": null,
  "descripcion": "LOS ESTUDIANTES DEBEN CONOCER LAS BASES QUÍMICAS Y FÍSICAS DE LA HERENCIA MEDIANTE LOS CUALES SE TRANSMITEN LAS CARACTERÍSTICAS DE PADRES A HIJOS, EMPLEANDO EN LO POSIBLE EJEMPLOS EN ANIMALES DOMÉSTICOS Y ENFATIZANDO EN LA PARTE QUE TENGA MAYOR APLICACIÓN EN MEDICINA VETERINARIA. LOS ESTUDIANTES ESTARÁN EN CAPACIDAD DE REALIZAR ANÁLISIS DE PEDIGRÍES PARA INFERIR LOS MECANISMOS DE CONTROL GENÉTICO DE LOS FENOTIPOS EN ESTUDIO, ADEMÁS CONOCERÁN LAS PRINCIPALES HERRAMIENTAS BIOTECNOLÓGICAS EMPLEADAS EN LA CITOGENÉTICA Y LA GENÉTICA MOLECULAR.",
  "contenido": null,
  "tipologia": "FUND. OBLIGATORIA",
  "via": "catalogo-sia"
 },
 "2017097|Virología": {
  "cod": "2017097",
  "nombre": "Virología",
  "vigente": true,
  "unidad": null,
  "creditos": 3,
  "semanas": null,
  "horas": null,
  "validable": null,
  "asistencia": null,
  "libreEleccion": null,
  "descripcion": "OBJETIVO\nProporcionar al estudiante conocimientos generales (teórico-prácticos) de los agentes virales y de las principales enfermedades que ocasionan en las especies domésticas, haciendo énfasis en su diagnóstico, y en las medidas que permitan prevenir, controlar y eventualmente erradicarlas, con el fin de consolidar los conceptos básicos para el ejercicio de la profesión médico veterinaria.\n\nMETODOLOGIA\nEl curso se desarrolla en dos modalidades: una teórica y otra práctica. La teoría esta sustentada en la presentación de conferencias magistrales, lectura de artículos científicos y participación del estudiante a través de la presentación de seminarios. La parte práctica se lleva a cabo a través de prácticas dirigidas y desarrolladas por los estudiantes.",
  "contenido": null,
  "tipologia": "DISCIPLINAR OBLIGATORIA",
  "via": "catalogo-sia"
 },
 "2017047|Bacteriología y micología": {
  "cod": "2017047",
  "nombre": "Bacteriología y micología",
  "vigente": true,
  "unidad": null,
  "creditos": 3,
  "semanas": null,
  "horas": null,
  "validable": null,
  "asistencia": null,
  "libreEleccion": null,
  "descripcion": "Proporcionar las bases conceptuales y prácticas que permitan al estudiante de Medicina Veterinaria el conocimiento de los microorganismos infecciosos, sus\ncaracterísticas biológicas, su importancia clínica y diagnóstico. Contribuir al conocimiento de las principales enfermedades infecciosas que pueden afectar\nespecies de relevancia económica así como su incidencia en salud y producción y su relevancia en salud pública e infectologia. Comprender los conceptos de\ncontrol microbiano que contribuyan a un buen desempeño en el campo clínico- quirúrgico. Conocer la importancia de la contaminación microbiana de los\nalimentos de origen animal, para contribuir a garantizar su inocuidad de estos desde la producción primaria. Estudiar las principales aplicaciones del uso de\nmicroorganismos en el campo de los alimentos y la biotecnología médica.\nComo objetivo terminal se espera contribuir a la formación de profesionales de la Medicina Veterinaria idóneos, responsables y éticos, con la capacidad de\nparticipar en la solución de problemas que atañen a la salud animal y la salud pública en Colombia.",
  "contenido": null,
  "tipologia": "DISCIPLINAR OBLIGATORIA",
  "via": "catalogo-sia"
 },
 "2017077|Parasitología": {
  "cod": "2017077",
  "nombre": "Parasitología",
  "vigente": true,
  "unidad": null,
  "creditos": 4,
  "semanas": null,
  "horas": null,
  "validable": null,
  "asistencia": null,
  "libreEleccion": null,
  "descripcion": "1.Reconocer los principales parásitos que afectan animales domésticos, reportados en Colombia.\n2.Descripción de localización, ciclos de vida y epidemiología de las principales especies de parásitos.\n3.Reconocer los signos clínicos de las principales enfermedades parasitarias en especies domésticas.\n4.Conocer las principales técnicas de diagnóstico en Parasitología Veterinaria.\n5.Establecer los lineamientos generales sobre esquemas terapéuticos de prevención y control en la solución de problemas parasitarios.\n6.Estructurar un concepto general del problema parasitario en contextos clínicos y/o productivos.",
  "contenido": null,
  "tipologia": "DISCIPLINAR OBLIGATORIA",
  "via": "catalogo-sia"
 },
 "2017076|Nutrición": {
  "cod": "2017076",
  "nombre": "Nutrición",
  "vigente": true,
  "unidad": null,
  "creditos": 2,
  "semanas": null,
  "horas": null,
  "validable": null,
  "asistencia": null,
  "libreEleccion": null,
  "descripcion": "OBJETIVOS\n\nDespués de completar el curso el estudiante debe ser capaz de:\n\nListar y describir los principales nutrientes presentes en los recursos alimenticios usados en alimentación animal en el trópico bajo, medio y alto de Colombia.\nExplicar los procesos de digestión, absorción y utilización de los diferentes recursos alimenticios disponibles para la alimentación de aves, cerdos y bovinos.\nEsquematizar las diferentes estrategias de análisis nutricionales, químicos y microbiológicos de los recursos alimenticios y definir los procedimientos de almacenamiento y conservación.\nExplicar la importancia de las proteínas, lípidos y carbohidratos en los sistemas de alimentación.\nDiscutir los requerimientos para crecimiento, mantenimiento y producción (leche, carne, huevos y reproducción)\nBalancear diferentes tipos de dietas completas, suplementos, premezclas y núcleos en las fases productivas de aves, cerdos y bovinos (estudio de caso).\nDescribir los principales sistemas de alimentación para la producción moderna de leche, carne y huevos en condiciones tropicales (estudio de caso).",
  "contenido": null,
  "tipologia": "DISCIPLINAR OBLIGATORIA",
  "via": "catalogo-sia"
 },
 "1000047|Inglés IV": {
  "cod": "1000047",
  "nombre": "Inglés IV- Semestral",
  "vigente": true,
  "unidad": null,
  "creditos": 3,
  "semanas": null,
  "horas": null,
  "validable": null,
  "asistencia": null,
  "libreEleccion": null,
  "descripcion": "El objetivo general de los cuatro niveles de lengua en el Programa ALEX es desarrollar la competencia comunicativa en la lengua extranjera elegida por el estudiante (con énfasis en comprensión de lectura) y, paralelamente, su capacidad para tomar decisiones con respecto al proceso de aprendizaje. Se espera que los estudiantes, al término del cuarto nivel puedan leer y comprender textos auténticos de tipo académico con mayor énfasis en reportes de tipo investigativo y argumentativo. Identifican, por lo tanto, los principales aspectos en un reporte de investigación y los argumentos y contra argumentos que aparecen en un ensayo. También participan de manera oral en debates en torno a situaciones de tipo académico y cultural y redactan textos con el rigor que se requiere para expresar su punto de vista con respecto a un tema específico y los diferentes argumentos que lo sustentan. Se cuenta con un Centro de Recursos que le brinda tanto a profesores como estudiantes un buen número de recursos para la enseñana y aprendizaje de la lengua y que se relacionan directamente con los contenidos que el curso plantea.",
  "contenido": null,
  "tipologia": "NIVELACIÓN",
  "via": "catalogo-sia"
 },
 "2017088|Semiología": {
  "cod": "2017088",
  "nombre": "Semiología",
  "vigente": true,
  "unidad": null,
  "creditos": 3,
  "semanas": null,
  "horas": null,
  "validable": null,
  "asistencia": null,
  "libreEleccion": null,
  "descripcion": "OBJETIVOS\n\n&#61607; ENSEÑAR A LOS ALUMNOS LA PROPEDEÚTICA CLÍNICA (PROCEDIMIENTO PARA EXAMINAR ADECUADAMENTE) APROPIADA PARA PODER EXTRAER Y OBTENER INFORMACIÓN MÉDICA BÁSICA DE LOS PACIENTES QUE EN UN MOMENTO ACTÚAN CON SIGNOS CLÍNICOS DE ENFERMEDAD.\n\n&#61607; DESARROLLAR EN LOS ESTUDIANTES LA HABILIDAD PARA ELABORAR ANÁLISIS CLÍNICOS Y CRÍTICOS A PARTIR DE LOS SIGNOS DE ENFERMEDAD CON EL OBJETO DE PROPONER O PLANTEAR HIPÓTESIS QUE LLEGUEN A EXPLICAR DE UNA MANERA APROXIMADA LO QUE EN REALIDAD PRESENTA EL ANIMAL ENFERMO (PROPONER DIAGNÓSTICOS DIFERENCIALES).\n\nMETODOLOGIA\n\nPRÁCTICAS: CLASES Y TRABAJO EN CLASE, TRABAJO DIRIGIDO EN LAS CLÍNICAS.\nTEÓRICA: TERMINOLOGÍA, CONCEPTOS Y ARTÍCULOS RECOMENDADOS.\nSEMINARIOS  TALLERES.",
  "contenido": null,
  "tipologia": "DISCIPLINAR OBLIGATORIA",
  "via": "catalogo-sia"
 },
 "2017060|Farmacología": {
  "cod": "2017060",
  "nombre": "Farmacología",
  "vigente": true,
  "unidad": null,
  "creditos": 4,
  "semanas": null,
  "horas": null,
  "validable": null,
  "asistencia": null,
  "libreEleccion": null,
  "descripcion": "OBJETIVOS\n\n&#61607; Adquirir conocimientos sobre los principios farmacodinámicos y farmacocinéticos\n&#61607; Que rigen la administración de los principales medicamentos veterinarios con el fin de producir los efectos clínicos deseados en los animales.\n\n&#61607; Relacionar los conocimientos farmacológicos teóricos con su administración Práctica a través de los casos clínicos que se tratan en las diferentes unidades clínicas de la Facultad y con las prácticas programadas en el desarrollo de la asignatura.\n\n&#61607; Conocer los preparados comerciales representativos del mercado colombiano en cuanto a: presentación, administración y dosificación a través de ejercicios de prescripción.\n\nNaturaleza: teórico-práctica\n\n\nMETODOLOGIA\n\nEl contenido se enseña a través de diferentes métodos de enseñanza : se utiliza la cátedra magistral, la aplicación de fármacos en animales domésticos (bovinos, equinos y pequeños animales), la presentación de casos clínicos por parte de los estudiantes para la correlación de los conocimientos teóricos y su aplicación práctica, elaboración de prescripciones sobre casos hipotéticos y la lectura de artículos seleccionados por parte del profesor.",
  "contenido": null,
  "tipologia": "DISCIPLINAR OBLIGATORIA",
  "via": "catalogo-sia"
 },
 "2017067|Mecanismos de enfermedad": {
  "cod": "2017067",
  "nombre": "Mecanismos de enfermedad",
  "vigente": true,
  "unidad": null,
  "creditos": 4,
  "semanas": null,
  "horas": null,
  "validable": null,
  "asistencia": null,
  "libreEleccion": null,
  "descripcion": "En esta cátedra el estudiante profundiza, comprende y actualiza los principios fisiopatológicos, es decir los\neventos y mecanismos inherentes al fenómeno de la enfermedad en sus distintas formas. El estudiante\nfundamenta una filosofía sólida del concepto de enfermedad para implementarla en sus asignaturas\nposteriores, estudios de posgrado y la vida profesional; es decir construir la estructura metódica correcta para\nformular diagnósticos diferenciales y definitivos correlacionando cada lesión, mecanismo de lesión y los\nposibles agentes inductores de la misma.",
  "contenido": null,
  "tipologia": "DISCIPLINAR OBLIGATORIA",
  "via": "catalogo-sia"
 },
 "2017064|Imagenología": {
  "cod": "2017064",
  "nombre": "Imagenología",
  "vigente": true,
  "unidad": null,
  "creditos": 1,
  "semanas": null,
  "horas": null,
  "validable": null,
  "asistencia": null,
  "libreEleccion": null,
  "descripcion": "Objetivo General: Orientar al estudiante de Medicina Veterinaria para que adquiera los conocimientos necesarios que le permitan realizar, interpretar y evaluar imágenes medicas diagnosticas.\nObjetivos Específicos: Comprender los aspectos físicos, funcionamiento y propiedades básicas de los equipos utilizados en la obtención de imágenes diagnósticas.\nFamiliarizarse con los riesgos y efectos adversos para la salud de los procesos que dan como resultado la obtención de una imagen diagnóstica, de manera que el estudiante implemente las medidas de protección necesarias para la minimización de dichos efectos.\nObtener y adquirir un método organizado, estructurado y sistemático que permita interpretar y evaluar imágenes diagnósticas obtenidas a través de las principales tecnologías disponibles en medicina veterinaria como radiología, ultrasonido, endoscopia, resonancia magnética y tomografía axial computarizada.\nMetodología: El cumplimiento de los objetivos se realizará a partir de clases magistrales sobre los temas específicos del programa, talleres prácticos que familiaricen al estudiante con las imágenes y trabajos teórico prácticos orientados a la integración de los conocimientos básicos con la práctica clínica veterinaria.",
  "contenido": null,
  "tipologia": "DISCIPLINAR OBLIGATORIA",
  "via": "catalogo-sia"
 },
 "2017091|Sociedades rurales": {
  "cod": "2017091",
  "nombre": "Sociedades rurales",
  "vigente": true,
  "unidad": null,
  "creditos": 3,
  "semanas": null,
  "horas": null,
  "validable": null,
  "asistencia": null,
  "libreEleccion": null,
  "descripcion": "OBJETIVOS:\nEl conocimiento de los grupos sociales que conforman la Sociedad Rural Colombiana (las diferentes formaciones regionales, las comunidades negras e indígenas, los trabajadores rurales, los empresarios agrícolas, el campesinado), la evolución y los procesos configurativos de estos grupos, el grado de desarrollo histórico y económico de nuestra sociedad rural, las diferentes formaciones socio-económicas que a su interior coexisten, y, principalmente, el reconocimiento de las culturas e ideologías propias a estos sectores sociales, es el objeto expreso de una Sociología Rural.",
  "contenido": null,
  "tipologia": "DISCIPLINAR OBLIGATORIA",
  "via": "catalogo-sia"
 },
 "2017052|Cirugía I": {
  "cod": "2017052",
  "nombre": "Cirugía I",
  "vigente": true,
  "unidad": null,
  "creditos": 4,
  "semanas": null,
  "horas": null,
  "validable": null,
  "asistencia": null,
  "libreEleccion": null,
  "descripcion": "OBJETIVOS DE LA ASIGNATURA\n1. Lograr que el estudiante comprenda los principios básicos de desinfección, antisepsia y asepsia y\npueda aplicarlos en un contexto clínico.\n2. Preparar al estudiante para llevar a cabo la anestesia general de un canino o un felino, de forma\nsegura y efectiva, así como el proceso de monitoreo de la misma.\n3. Desarrollar las competencias quirúrgicas básicas, de modo que el estudiante esté en capacidad\nde llevar a cabo los procedimientos quirúrgicos electivos más comunes en cirugía de pequeños\nanimales: suturas en general, ovariohisterectomía y orquiectomía.\n4. Familiarizar al estudiante con la realización de procedimientos quirúrgicos más complejos como\nson: laparotomía exploratoria, esplenectomía, cirugía genitourinaria y cirugía gastrointestinal.\n5. Brindar al estudiante conceptos básicos de la realización de cirugías de alta complejidad: cirugía\nortopédica y cirugía oftalmológica.",
  "contenido": null,
  "tipologia": "DISCIPLINAR OBLIGATORIA",
  "via": "catalogo-sia"
 },
 "2017078|Patología clínica": {
  "cod": "2017078",
  "nombre": "Patología clínica",
  "vigente": true,
  "unidad": null,
  "creditos": 3,
  "semanas": null,
  "horas": null,
  "validable": null,
  "asistencia": null,
  "libreEleccion": null,
  "descripcion": "LA ASIGNATURA PRETENDE INTEGRAR LOS CONOCIMIENTOS DE ÁREAS BÁSICAS COMO: ANATOMÍA, FISIOLOGÍA, PATOLOGÍA, SEMIOLOGÍA ENTRE OTRAS, A UN MARCO TEÓRICO DE PATOLOGÍA CLÍNICA, CON EL OBJETO DE INTERPRETAR RESULTADOS DE LABORATORIO A LA LUZ DE UN CUADRO CLÍNICO DEFINIDO SIGUIENDO EL MODELO DE PROBLEMA ORIENTADO.\n\nLA ASIGNATURA DE PATOLOGÍA CLÍNICA, PRETENDE DE MANERA PRIORITARIA DESARROLLAR EN LOS ESTUDIANTES DINÁMICAS DE ESTUDIO BASADAS EN LA CORRELACIÓN DE RESULTADOS DE LABORATORIO Y CASOS CLÍNICOS REALES. POR TAL MOTIVO NO FAVORECE LOS PROCESOS MEMORISTICOS, SINO LOS ANALÍTICOS.",
  "contenido": null,
  "tipologia": "DISCIPLINAR OBLIGATORIA",
  "via": "catalogo-sia"
 },
 "2017079|Patología sistémica": {
  "cod": "2017079",
  "nombre": "Patología sistémica",
  "vigente": true,
  "unidad": null,
  "creditos": 4,
  "semanas": null,
  "horas": null,
  "validable": null,
  "asistencia": null,
  "libreEleccion": null,
  "descripcion": "OBJETIVOS\nSE BUSCA QUE DURANTE EL CURSO EL ESTUDIANTE:\n&sect; APRENDA LAS TÉCNICAS DE NECROPSIA, FORMA Y ENVÍO SE MUESTRAS PARA LOS DIFERENTES LABORATORIOS DE DIAGNÓSTICO ( HISTOPATOLOGÍA, TOXICOLOGÍA, MICROBIOLOGÍA Y PARASITOLOGÍA).\n&sect; ADQUIERA LA HABILIDAD PARA DESCRIBIR LAS ALTERACIONES ANATOMOPATOLÓGICAS OBSERVADAS Y PUEDA LLENAR LOS FORMATOS DE NECROPSIA RESPECTIVOS.\n&sect; DESPERTAR LA HABILIDAD DEL ESTUDIANTE PARA CORRELACIONAR LAS ALTERACIONES MACRO Y MICROSCÓPICAS Y ASÍ CONSEGUIR DIAGNÓSTICOS DIFERENCIALES DE LA CASUÍSTICA. ESTIMULAR LA CAPACIDAD INVESTIGATIVA Y CREATIVA PARA ORGANIZAR DIAGNÓSTICOS DEFINITIVOS DE LA CASUÍSTICA.\n\nSE HACE ESPECIAL ÉNFASIS PARA QUE SE REFLEXIONE EN CADA UNA DE LAS ENFERMEDADES DISCUTIDAS EN:\n IMPACTO ECONÓMICO EN LOS SISTEMAS DE PRODUCCIÓN.\n RELIEVANCIA DE LAS ENFERMEDADES EN LOS MERCADOS NACIONALES E INTERNACIONALES.\n FUNCIÓN DEL MÉDICO VETERINARIO COMO PARTE DE LA SOCIEDAD CIENTÍFICA, TECNOLÓGICA, ECONÓMICA Y ÉTICA DEL PAÍS.\n ENFERMEDADES ZOONÓTICAS Y LA IMPORTANCIA DEL MÉDICO VETERINARIO COMO ACTOR PROTAGONISTA EN LA VIGILANCIA, PREVENCIÓN, CONTROL Y EDUCACIÓN EN ESTAS ENFERMEDADES.\n SE INSISTE EN LA OBLIGACIÓN PROFESIONAL DE ENTENDER Y PRACTICAR LA OBLIGATORIEDAD DE DECLARAR AQUELLAS ENFERMEDADES QUE ASÍ EXIGEN LAS AUTORIDADES SANITARIAS DEL PAÍS.",
  "contenido": null,
  "tipologia": "DISCIPLINAR OBLIGATORIA",
  "via": "catalogo-sia"
 },
 "2017255|Política agropecuaria": {
  "cod": "2017255",
  "nombre": "Política agropecuaria",
  "vigente": true,
  "unidad": null,
  "creditos": 3,
  "semanas": null,
  "horas": null,
  "validable": null,
  "asistencia": null,
  "libreEleccion": null,
  "descripcion": null,
  "contenido": null,
  "tipologia": "DISCIPLINAR OBLIGATORIA",
  "via": "catalogo-sia"
 },
 "2017053|Cirugía II": {
  "cod": "2017053",
  "nombre": "Cirugía II",
  "vigente": true,
  "unidad": null,
  "creditos": 2,
  "semanas": null,
  "horas": null,
  "validable": null,
  "asistencia": null,
  "libreEleccion": null,
  "descripcion": "La asignatura busca desarrollar los conocimientos y las habilidades necesarias para resolver los problemas quirúrgicos que se presentan con mayor frecuencia en los Bovinos, Equinos, Ovinos, Caprinos y Porcinos. Se revisaran en especial, aquellas intervenciones que se puedan llevar a cabo en condiciones de campo, es decir las que no requieren facilidades quirúrgicas especializadas. Se llevaran a cabo prácticas con piezas anatómicas para los procedimientos que lo permitan y en algunos casos se utilizarán pacientes de la clínica de Grandes Animales o de los hatos de la Facultad. Se realizaran cuatro parciales teóricos asi: en la semana 3, 8, 13 y en la 16. Los parciales tendran un valor de 20%. El 20% restante será un ensayo sobre un tema de libre escogencia, relacionado con la cátedra y que deberá ser escrito a mano con una extension máxima de 5 hojas, y deberá entregarse en la semana 12.",
  "contenido": null,
  "tipologia": "DISCIPLINAR OBLIGATORIA",
  "via": "catalogo-sia"
 },
 "2017093|Toxicología": {
  "cod": "2017093",
  "nombre": "Toxicología",
  "vigente": true,
  "unidad": null,
  "creditos": 3,
  "semanas": null,
  "horas": null,
  "validable": null,
  "asistencia": null,
  "libreEleccion": null,
  "descripcion": "1. BRINDAR EL CONOCIMIENTO BÁSICO DE LA TOXICOLOGÍA GENERAL PARA CAPACITAR AL ESTUDIANTE EN LA INTERPRETACIÓN POSTERIOR DE PROCESOS TOXICOLÓGICOS ESPECÍFICOS.\n2. REVISAR LAS PRINCIPALES INTOXICACIONES QUE SE PRESENTAN EN LOS ANIMALES DOMÉSTICOS EN EL CONTEXTO MUNDIAL Y COLOMBIANO.\n3. OFRECER UNA METODOLOGÍA PEDAGÓGICA QUE LE PERMITA AL ESTUDIANTE LA EJECUCIÓN DE ACTIVIDADES INDIVIDUALES Y EN GRUPO, TANTO EN SESIONES PRESENCIALES COMO NO PRESENCIALES\nCAPACITAR AL ESTUDIANTE EN LA COMUNICACIÓN DE TIPO CIENTÍFICO A TRAVÉS DE SEMINARIOS Y/O POSTERS Y/O ARTÍCULOS CIENTÍFICOS.\n\nMETODOLOGÍA:\n\n CLASES MAGISTRALES Y SESIONES PRÁCTICAS CONDUCIDAS POR EL PROFESOR ENCARGADO.\n\n DISCUSIÓN DE LECTURAS Y ARTÍCULOS ASIGNADOS\n\n TRABAJO AUTÓNOMO DEL ESTUDIANTE: CONSULTA DE LITERATURA ESPECIALIZADA PARA REALIZAR TALLERES Y TRABAJOS (POSTER Y ARTÍCULO INDIVIDUAL) SOBRE PRÁCTICAS.",
  "contenido": null,
  "tipologia": "DISCIPLINAR OBLIGATORIA",
  "via": "catalogo-sia"
 },
 "2017058|Epidemiología": {
  "cod": "2017058",
  "nombre": "Epidemiología",
  "vigente": true,
  "unidad": null,
  "creditos": 3,
  "semanas": null,
  "horas": null,
  "validable": null,
  "asistencia": null,
  "libreEleccion": null,
  "descripcion": "OBJETIVOS\n\nPROMOVER UN CAMBIO DE ACTITUD EN LO QUE TIENE QUE VER CON LA SOLUCIÓN DE LIMITANTES DE LA SALUD CON CRITERIOS COLECTIVOS, ENFOCADO TANTO A LAS MAYORÍAS SANAS COMO A LAS MINORÍAS ENFERMAS.\n\nRECONOCER Y SABER APLICAR LOS MÉTODOS Y TÉCNICAS DE LA MEDICINA PREVENTIVA AL CONOCIMIENTO DE LA SITUACIÓN DE SALUD Y ENFERMEDAD EN LAS POBLACIONES ANIMALES.\n\nFAMILIARIZAR AL ESTUDIANTE CON LOS MÉTODOS Y LAS TÉCNICAS DE CAPTURA, ANÁLISIS Y DIFUSIÓN DE INFORMACIÓN EN LOS QUE A MEDICINA PREVENTIVA Y EPIDEMIOLOGÍA SE REFIERE.\n\nMETODOLOGIA\n\nEL CURSO SE REALIZA MEDIANTE CONFERENCIAS MAGISTRALES, CONFERENCISTAS INVITADOS, EJERCICIOS PARA DESARROLLAR FUERA DEL AULA Y PRESENTACIÓN DE INFORMES, ASÍ COMO TRABAJOS ESPECIALES.",
  "contenido": null,
  "tipologia": "DISCIPLINAR OBLIGATORIA",
  "via": "catalogo-sia"
 },
 "2017074|Medicina aviar": {
  "cod": "2017074",
  "nombre": "Medicina aviar",
  "vigente": true,
  "unidad": null,
  "creditos": 3,
  "semanas": null,
  "horas": null,
  "validable": null,
  "asistencia": null,
  "libreEleccion": null,
  "descripcion": "Con el compromiso de nutrir a la humanidad la industria avícola exige altos estándares de producción, lo que facilita la presentación de enfermedades en los sistemas de explotación afectando la sanidad animal y la calidad de huevos y carne. Esta situación exige de profesionales de alto nivel en el área. Al finalizar la cátedra los estudiantes adquirirán las competencias necesarias para identificar y diagnosticar las diferentes patologías y trastornos metabólicos que afectan a las aves, desarrollando un pensamiento crítico que lleve a la correcta toma de decisiones en la solución de problemas sanitarios y productivos en diferentes tipos de aves de corral.",
  "contenido": null,
  "tipologia": "DISCIPLINAR OBLIGATORIA",
  "via": "catalogo-sia"
 },
 "2017080|Planeación y evaluación de empresas agropecuarias": {
  "cod": "2017080",
  "nombre": "Planeación y evaluación de empresas agropecuarias",
  "vigente": true,
  "unidad": null,
  "creditos": 2,
  "semanas": null,
  "horas": null,
  "validable": null,
  "asistencia": null,
  "libreEleccion": null,
  "descripcion": "Este curso pretende brindar a los estudiantes los elementos necesarios para realizar el proceso de formulación y evaluación de una empresa agropecuaria o de servicios veterinarios, de forma sencilla y clara, de manera que el futuro profesional pueda aplicar estos conceptos en el desarrollo de un proyecto real propio, o en beneficio de un tercero. En el desarrollo del curso se analizará, en primer término, el concepto de administración, su importancia y funciones. Al estudiante se le dará una introducción acerca del sector en que desarrollará su vida profesional. Se estudiarán los fundamentos de mercadeo, los aspectos relacionados con la creación de sus estrategias; y cómo crear una empresa que pueda resultar viable y exitosa. En ese sentido se le dará información básica relacionada con el proceso para la constitución de una empresa así como las exigencias de orden legal que de ellos se deriva. En segundo término, se observarán las herramientas relacionadas con los procesos de planificación y evaluación, de manera que se permita desarrollar procesos con competitividad y rentabilidad de acuerdo a los productos, bienes o servicios que se ofrezcan.",
  "contenido": null,
  "tipologia": "DISCIPLINAR OBLIGATORIA",
  "via": "catalogo-sia"
 },
 "2017059|Extensión y desarrollo rural": {
  "cod": "2017059",
  "nombre": "Extensión y desarrollo rural",
  "vigente": true,
  "unidad": null,
  "creditos": 1,
  "semanas": null,
  "horas": null,
  "validable": null,
  "asistencia": null,
  "libreEleccion": null,
  "descripcion": "EL SECTOR RURAL EN UN PAÍS COMO COLOMBIA CONSTITUYE UNO DE LOS PILARES PARA SU DESARROLLO, POR ESTA RAZÓN RESULTA DE GRAN IMPORTANCIA EL ANÁLISIS DE LA PROBLEMÁTICA QUE LO AFECTA. ESTE CURSO SE DIVIDE EN TRES GRANDES ÉNFASIS TEMÁTICOS. PRIMERO, EL DEBATE SOBRE LOS ASPECTOS RELACIONADOS CON LA IDEA DEL DESARROLLO Y LAS PERSPECTIVAS DEL MISMO; SEGUNDO, EL DEBATE SOBRE LA ORIENTACIÓN DEL DESARROLLO RURAL Y SUS PRINCIPALES POLÍTICAS; Y TERCERO, LA ELABORACIÓN DE UN PROYECTO PRODUCTIVO POR PARTE DE LOS ESTUDIANTES. AUNQUE LA DISCUSIÓN SOBRE ESTOS TEMAS ES MUY COMPLEJA, CON ESTE CURSO SE PRETENDE BRINDAR A LOS ESTUDIANTES ELEMENTOS PARA ASUMIR UNA POSICIÓN CRÍTICA FRENTE A ELLOS, CON EL FIN DE PROPICIAR EL DEBATE AL INTERIOR DEL GRUPO SOBRE LA ORIENTACIÓN DEL DESARROLLO RURAL EN LOS AÑOS VENIDEROS.OBJETIVO GENERAL\n\nOFRECER AL ESTUDIANTE LOS ELEMENTOS NECESARIOS PARA EL DEBATE SOBRE LOS TEMAS RELACIONADOS CON EL DESARROLLO RURAL EN COLOMBIA.\n\nOBJETIVOS ESPECIFICOS\n\n1. OFRECER AL ESTUDIANTE LOS ELEMENTOS HISTÓRICOS NECESARIOS SOBRE LA EVOLUCIÓN DE LAS TEORÍAS DEL DESARROLLO Y EN PARTICULAR DEL DESARROLLO RURAL EN NUESTRO PAÍS, PARA QUE BASADOS EN ELLOS, SE CREE UNA POSICIÓN PROPIA SOBRE ESTE TEMA EN PARTICULAR.\n2. FOMENTAR LA DISCUSIÓN ARGUMENTADA SOBRE LAS TEMÁTICAS TRATADAS, RESPETANDO LAS POSICIONES CONTRARIAS COMO PARTE DE UN EJERCICIO DE TOLERANCIA NECESARIO EN UNA SOCIEDAD QUE VIVE EN MEDIO DE UN CONTINUO CONFLICTO.\n3. ACOMPAÑAR AL ESTUDIANTE EN EL PROCESO DE ELABORACIÓN DE UN PROYECTO DE DESARROLLO, EL CUAL SEA REALIZABLE EN EL CORTO PLAZO.",
  "contenido": null,
  "tipologia": "DISCIPLINAR OBLIGATORIA",
  "via": "catalogo-sia"
 },
 "2017070|Medicina interna de pequeños": {
  "cod": "2017070",
  "nombre": "Medicina interna de pequeños",
  "vigente": true,
  "unidad": null,
  "creditos": 2,
  "semanas": null,
  "horas": null,
  "validable": null,
  "asistencia": null,
  "libreEleccion": null,
  "descripcion": "OBJETIVOS\n\n&#61559; Estudiar las diferentes entidades clínicas que afectan más comunmente a los animales de compañía.\n\n&#61559; Este estudio será desde la perspectiva de la Medicina Interna pero complementado con un enfoque epidemiológico.\n\n&#61559; Desarrollar en los estudiantes capacidades para resolver problemas médicos individuales y poblacionales.\n\n&#61559; Desarrollar en los estudiantes las habilidades del pensar clínico.\n\n&#61559; Que este curso sirva de integrador de las ciencias básicas al pensar clínico para así poder diagnosticar, evolucionar, manejar, resolver, prevenir y controlar las diferentes entidades clínicas.",
  "contenido": null,
  "tipologia": "DISCIPLINAR OBLIGATORIA",
  "via": "catalogo-sia"
 },
 "2017072|Medicina interna de rumiantes": {
  "cod": "2017072",
  "nombre": "Medicina interna de rumiantes",
  "vigente": true,
  "unidad": null,
  "creditos": 2,
  "semanas": null,
  "horas": null,
  "validable": null,
  "asistencia": null,
  "libreEleccion": null,
  "descripcion": "Objetivos del Curso:\n\n Estudiar las diferentes entidades clínicas que afectan más comúnmente a los rumiantes (Bovinos, Ovinos y caprinos)\n El estudio de las entidades se hará desde la perspectiva de la medicina interna y un componente adecuado de la epidemiologia. Los aspectos quirúrgicos serán contemplados en las entidades que lo demanden.\n Complementar los aspectos de la enfermedad y la sanidad en el contexto de medicina de la producción\n Desarrollará en los estudiantes los conocimientos y habilidades médicas que permitan un adecuado enfoque y solución de problemas tanto individuales como poblacionales\n Desarrollar habilidades en el quehacer y en el pensar Clínico\n Integrar las ciencias básicas, al pensar clínico con el objeto de diagnosticar, evolucionar, manejar, resolver, prevenir y controlar las diferentes entidades clínicas\n Contribuir en el estudiante a que se desarrolle un componente importante en el proceso de la adquisición de conocimiento de manera autónoma.\n Contribuir al proceso ético en el ejercicio de la Medicina Veterinaria en su quehacer clínico",
  "contenido": null,
  "tipologia": "DISCIPLINAR OBLIGATORIA",
  "via": "catalogo-sia"
 },
 "2017087|Salud pública": {
  "cod": "2017087",
  "nombre": "Salud pública",
  "vigente": true,
  "unidad": null,
  "creditos": 4,
  "semanas": null,
  "horas": null,
  "validable": null,
  "asistencia": null,
  "libreEleccion": null,
  "descripcion": "OBJETIVOS: Se espera que al terminar el módulo el estudiante esté en capacidad de:\n\n1. Analizar de manera crítica la relación medio ambiente, desarrollo económico y salud\n2. Participar en el proceso de vigilancia epidemiológica de enfermedades zoonóticas\n3. Reconocer el papel del médico veterinario en salud pública\n4. Identificar la cadena epidemiológica, diagnóstico, factores deriesgo, prevención y control de las principales zoonosis emergentes y reemergentes\n5.Identificar la cadena epidemiológica, diagnóstico, factores deriesgo, prevención y control de las principales enfermedades transmitidas por vectores\n6. Reconocer las diferencias entre estudios cuantitativos y cualitativos, conocer la metodología de algunos estudios cualitativos y aplicar uno de ellos a una situación real y de interés en salud pública\n7. Aplicar y reconocer la importancia de las normas de bioseguridad en su ejercicio práctico como futuro médico veterinario\n8. Promocionar e incorporar estilos de vida saludable\n9. Diseñar y aplicar estrategias de educación en salud, dirigidas a la comunidad",
  "contenido": null,
  "tipologia": "DISCIPLINAR OBLIGATORIA",
  "via": "catalogo-sia"
 },
 "2017068|Salud de hato": {
  "cod": "2017068",
  "nombre": "Salud de hato",
  "vigente": true,
  "unidad": null,
  "creditos": 3,
  "semanas": null,
  "horas": null,
  "validable": null,
  "asistencia": null,
  "libreEleccion": null,
  "descripcion": "La asignatura está diseñada para estudiantes de pregrado que cursan la carrera de Medicina Veterinaria, por tanto pretende introducir al estudiante a las metodologías asociadas al entendimiento, desarrollo e implementación del concepto del problema orientado (diagnostico basado en la evidencia) aplicado a la medicina de poblaciones. El curso busca enfatizar en el uso herramientas de tipo epidemiológico para evaluar el impacto, la evolución y el curso de las enfermedades y otras problemáticas de salud en grupos de animales de producción. Se discutirá el uso de técnicas cualitativas y cuantitativas para facilitar el análisis de la información obtenida de los hatos o grupos de animales de producción y su correcta interpretación, con el fin de orientar el diagnostico poblacional de una manera mas adecuada y eficiente. Se busca discutir elementos suficientes y técnicas para de la investigación de enfermedades, que afectan de la productividad y del bienestar en poblaciones de animales y establecer los factores de riesgo de las mismas con miras el establecimiento de medidas de control y prevención adecuadas.\nMetodología: El curso es de carácter teórico práctico y se desarrollará mediante charlas magistrales, apoyadas con ayudas audiovisuales, prácticas de manejo de datos y programas de computador, lecturas de artículos científicos, y presentación y discusión de casos clínicos.\nObjetivo:Se espera que el estudiante este en capacidad de diseñar e implementar metodologías de aproximación diagnostica poblacional con miras a elaborar planes de intervención tanto de tipo diagnóstico como terapéutico para la solución, monitoreo y evaluación de problemáticas que afectan la productividad de los diferentes sistemas de producción. Con el fin ultimo de implementar métodos de control prevención adecuados.",
  "contenido": null,
  "tipologia": "DISCIPLINAR OBLIGATORIA",
  "via": "catalogo-sia"
 },
 "2017084|Teriogenología I": {
  "cod": "2017084",
  "nombre": "Teriogenología I",
  "vigente": true,
  "unidad": null,
  "creditos": 2,
  "semanas": null,
  "horas": null,
  "validable": null,
  "asistencia": null,
  "libreEleccion": null,
  "descripcion": "OBJETIVOS\n\n1. Dar a conocer al estudiante los principios generales de la reproducción animal, profundizando en el estudio de los eventos reproductivos tanto de hembras como de machos, teniendo en cuenta la fisiopatología de los eventos, el diagnóstico y la terapéutica dentro del marco de la práctica de la Ginecología, la Obstetricia y la Andrología.(Teriogenología)\n2. Capacitar al estudiante para el diseño y ejecución de programas sobre inseminación artificial y el manejo reproductivo de un hato.\n3. Dar a conocer el sistema de registros con el fin de determinar parámetros reproductivos que permitan evaluar y mejorarlos a la vez que se realiza un diagnóstico de población.\n4. Capacitar al estudiante en los diferentes métodos de diagnóstico del estado reproductivo de la hembra y el macho bovino\n5. Dar a conocer al estudiante las técnicas especiales relacionadas con el manejo de semen, embriones y fertilización in vitro. En bovinos\n6. Dar a conocer aspectos del manejo reproductivo en bovinos, y búfalos",
  "contenido": null,
  "tipologia": "DISCIPLINAR OBLIGATORIA",
  "via": "catalogo-sia"
 },
 "2017069|Medicina interna de equinos": {
  "cod": "2017069",
  "nombre": "Medicina interna de equinos",
  "vigente": true,
  "unidad": null,
  "creditos": 2,
  "semanas": null,
  "horas": null,
  "validable": null,
  "asistencia": null,
  "libreEleccion": null,
  "descripcion": "Objetivos del Curso:\n Estudiar las diferentes entidades clínicas que afectan mas comúnmente a los equinos\n El estudio de las entidades se hará desde la perspectiva de la medicina interna y un componente adecuado de la epidemiologia. Los aspectos quirúrgicos serán contemplados en las entidades que lo demanden.\n Desarrollará en los estudiantes los conocimientos y habilidades médicas que permitan un adecuado enfoque y solución de problemas tanto individuales como poblacionales\n Desarrollar habilidades en el quehacer y en el pensar Clínico\n Integrar las ciencias básicas, al pensar clínico con el objeto de diagnosticar, evolucionar, manejar, resolver, prevenir y controlar las diferentes entidades clínicas\n Contribuir en el estudiante a que se desarrolle un componente importante en el proceso de la adquisición de conocimiento de manera autónoma.\n Contribuir al proceso ético en el ejercicio de la Medicina Veterinaria en su quehacer clínico",
  "contenido": null,
  "tipologia": "DISCIPLINAR OBLIGATORIA",
  "via": "catalogo-sia"
 },
 "2017071|Medicina interna de porcinos": {
  "cod": "2017071",
  "nombre": "Medicina interna de porcinos",
  "vigente": true,
  "unidad": null,
  "creditos": 2,
  "semanas": null,
  "horas": null,
  "validable": null,
  "asistencia": null,
  "libreEleccion": null,
  "descripcion": "La cátedra se desarrollará por medio de presentaciones magistrales, revisión y análisis de\nartículos técnico-científicos en cada tema.\nSe realizarán talleres en clase para discusiones analíticas de casos de campo integrando\naspectos de producción, clínicos, patológicos, epidemiológicos, diagnósticos diferenciales,\nherramientas para el diagnóstico, medidas de control, prevención y/eliminación.\nSe contará con la participación conferencistas invitados sobre temas particulares\nrelacionados con el programa de la asignatura.",
  "contenido": null,
  "tipologia": "DISCIPLINAR OBLIGATORIA",
  "via": "catalogo-sia"
 },
 "2017073|Medicina interna de silvestres": {
  "cod": "2017073",
  "nombre": "Medicina interna de silvestres",
  "vigente": true,
  "unidad": null,
  "creditos": 2,
  "semanas": null,
  "horas": null,
  "validable": null,
  "asistencia": null,
  "libreEleccion": null,
  "descripcion": "La medicina de silvestres es un campo de reciente desarrollo a nivel nacional y mundial, que ha venido incorporándose al acontecer veterinario con creciente importancia. Colombia es uno de los países con mayor riqueza de especies faunísticas, por lo tanto se hace necesario generar conocimientos sobre la fauna nativa, con miras a su mejor aprovechamiento y conservación. Por esta razón, la Facultad de Medicina Veterinaria y Zootecnia de la Universidad Nacional, afronta el reto de asumir su participación en este\ncampo.\n\nEl objetivo de la asignatura es capacitar los alumnos de la carrera de Medicina Veterinaria en aspectos de manejo y\nmedicina de especies silvestres colombianas mantenidas en cautiverio, y de especies\nexóticas consideradas mascotas de tenencia legal o de presentación frecuente en\ncolecciones zoológicas.",
  "contenido": null,
  "tipologia": "DISCIPLINAR OBLIGATORIA",
  "via": "catalogo-sia"
 },
 "2017085|Teriogenología II": {
  "cod": "2017085",
  "nombre": "Teriogenología II",
  "vigente": true,
  "unidad": null,
  "creditos": 2,
  "semanas": null,
  "horas": null,
  "validable": null,
  "asistencia": null,
  "libreEleccion": null,
  "descripcion": null,
  "contenido": null,
  "tipologia": "DISCIPLINAR OBLIGATORIA",
  "via": "catalogo-sia"
 },
 "2017054|Clínica de grandes animales": {
  "cod": "2017054",
  "nombre": "Clínica de grandes animales",
  "vigente": true,
  "unidad": null,
  "creditos": 8,
  "semanas": null,
  "horas": null,
  "validable": null,
  "asistencia": null,
  "libreEleccion": null,
  "descripcion": null,
  "contenido": null,
  "tipologia": "DISCIPLINAR OBLIGATORIA",
  "via": "catalogo-sia"
 },
 "2017056|Clínica de pequeños animales": {
  "cod": "2017056",
  "nombre": "Clínica de pequeños animales",
  "vigente": true,
  "unidad": null,
  "creditos": 8,
  "semanas": null,
  "horas": null,
  "validable": null,
  "asistencia": null,
  "libreEleccion": null,
  "descripcion": null,
  "contenido": null,
  "tipologia": "DISCIPLINAR OBLIGATORIA",
  "via": "catalogo-sia"
 },
 "2017055|Clínica de la reproducción": {
  "cod": "2017055",
  "nombre": "Clínica de la reproducción",
  "vigente": true,
  "unidad": null,
  "creditos": 8,
  "semanas": null,
  "horas": null,
  "validable": null,
  "asistencia": null,
  "libreEleccion": null,
  "descripcion": "Rotación por la Clínica de Reproducción, que le permite al estudiante familiarizarse con la casuística, atender a los pacientes y poner en práctica los conocimientos adquiridos durante la carrera.",
  "contenido": null,
  "tipologia": "DISCIPLINAR OBLIGATORIA",
  "via": "catalogo-sia"
 },
 "2017086|Rotación por laboratorios": {
  "cod": "2017086",
  "nombre": "Rotación por laboratorios",
  "vigente": true,
  "unidad": null,
  "creditos": 8,
  "semanas": null,
  "horas": null,
  "validable": null,
  "asistencia": null,
  "libreEleccion": null,
  "descripcion": null,
  "contenido": null,
  "tipologia": "DISCIPLINAR OBLIGATORIA",
  "via": "catalogo-sia"
 },
 "2017249|Trabajo de grado": {
  "cod": "2017249",
  "nombre": "Trabajo de Grado",
  "vigente": true,
  "unidad": null,
  "creditos": 10,
  "semanas": null,
  "horas": null,
  "validable": null,
  "asistencia": null,
  "libreEleccion": null,
  "descripcion": null,
  "contenido": null,
  "tipologia": "TRABAJO DE GRADO",
  "via": "catalogo-sia"
 },
 "1000009|Biología general": {
  "cod": "1000009",
  "nombre": "Biología general",
  "vigente": true,
  "unidad": null,
  "creditos": 3,
  "semanas": null,
  "horas": null,
  "validable": null,
  "asistencia": null,
  "libreEleccion": null,
  "descripcion": "La Biología es una disciplina fundamental que estudia los seres vivos, sus procesos vitales, su diversidad, evolución e interacción con el ambiente. Este curso de pregrado proporciona una formación integral en los principios biológicos que explican la organización y funcionamiento de la vida desde el nivel molecular hasta los ecosistemas, promoviendo el pensamiento científico, sistémico y crítico.\nA lo largo del curso, los estudiantes comprenderán la estructura y función celular, la genética, la herencia, el metabolismo, la evolución, la biodiversidad, la fisiología de organismos, la ecología y las relaciones entre ciencia, sociedad y ambiente. Asimismo, se fortalecerán competencias para interpretar fenómenos biológicos, analizar problemáticas ambientales y de salud, desarrollar habilidades experimentales y aplicar el conocimiento biológico a contextos reales y multidisciplinarios.\nAl finalizar el curso, el estudiante estará en capacidad de:\n¿ Explicar los principios fundamentales de la organización biológica.\n¿ Relacionar estructura y función en los diferentes niveles de organización de la vida.\n¿ Interpretar procesos biológicos desde una perspectiva sistémica e integradora.\n¿ Aplicar conceptos biológicos en la solución de problemas ambientales, sociales y de salud.\n¿ Reconocer la importancia ética y social del conocimiento biológico en la toma de decisiones responsables.\nEste curso constituye una base esencial para programas de ciencias naturales, ciencias de la salud, ingenierías, ciencias ambientales, educación y áreas afines, favoreciendo la formación de profesionales críticos, éticos y comprometidos con la sustentabilidad y la transformación social.",
  "contenido": null,
  "tipologia": "FUND. OPTATIVA",
  "via": "catalogo-sia"
 },
 "1000010|Biología molecular y celular": {
  "cod": "1000010",
  "nombre": "Biología molecular y celular",
  "vigente": true,
  "unidad": null,
  "creditos": 3,
  "semanas": null,
  "horas": null,
  "validable": null,
  "asistencia": null,
  "libreEleccion": null,
  "descripcion": null,
  "contenido": null,
  "tipologia": "FUND. OPTATIVA",
  "via": "catalogo-sia"
 },
 "1000011|Fundamentos de ecología": {
  "cod": "1000011",
  "nombre": "Fundamentos de ecología",
  "vigente": true,
  "unidad": null,
  "creditos": 3,
  "semanas": null,
  "horas": null,
  "validable": null,
  "asistencia": null,
  "libreEleccion": null,
  "descripcion": "La asignatura ECOLOGIA busca dar las bases fundamentales del funcionamiento de los sistemas ecológicos a sus diferentes escalas y hacer visible las relaciones entre estos sistemas de organización a escala ecológica. El curso también pretende mostrar los t",
  "contenido": null,
  "tipologia": "FUND. OPTATIVA",
  "via": "catalogo-sia"
 },
 "2017092|Suelos y plantas": {
  "cod": "2017092",
  "nombre": "Suelos y plantas",
  "vigente": true,
  "unidad": null,
  "creditos": 2,
  "semanas": null,
  "horas": null,
  "validable": null,
  "asistencia": null,
  "libreEleccion": null,
  "descripcion": null,
  "contenido": null,
  "tipologia": "DISCIPLINAR OPTATIVA",
  "via": "catalogo-sia"
 },
 "2017089|Sistemas de producción I": {
  "cod": "2017089",
  "nombre": "Sistemas de producción I",
  "vigente": true,
  "unidad": null,
  "creditos": 2,
  "semanas": null,
  "horas": null,
  "validable": null,
  "asistencia": null,
  "libreEleccion": null,
  "descripcion": null,
  "contenido": null,
  "tipologia": "DISCIPLINAR OPTATIVA",
  "via": "catalogo-sia"
 },
 "2017090|Sistemas de producción II": {
  "cod": "2017090",
  "nombre": "Sistemas de producción II",
  "vigente": true,
  "unidad": null,
  "creditos": 2,
  "semanas": null,
  "horas": null,
  "validable": null,
  "asistencia": null,
  "libreEleccion": null,
  "descripcion": "Partiendo del qué hacer y perfil profesional del Médico Veterinario, centrado en tres campos específicos: Atención, protección y bienestar animal; protección de la salud humana y del entorno y Medicina de la producción y sanidad Animal. En este contexto, desde el espacio académico Sistemas de Producción I, se pretende capacitar al estudiante para identificar factores tecnológicos y no tecnológicos que determinan el óptimo desempeño, salud y bienestar animal en sistemas de producción aviar, porcina y pequeños rumiantes, comprender el gran compromiso social que es velar por la inocuidad de los productos generados en los sistemas de producción animal en procura por la seguridad alimentaria, que ampare el uso responsable de los recursos naturales asegurando la sostenibilidad del sistema.",
  "contenido": null,
  "tipologia": "DISCIPLINAR OPTATIVA",
  "via": "catalogo-sia"
 },
 "2017137|Nutrición y alimentación I": {
  "cod": "2017137",
  "nombre": "Nutrición y alimentación I",
  "vigente": true,
  "unidad": null,
  "creditos": 4,
  "semanas": null,
  "horas": null,
  "validable": null,
  "asistencia": null,
  "libreEleccion": null,
  "descripcion": null,
  "contenido": null,
  "tipologia": "DISCIPLINAR OPTATIVA",
  "via": "catalogo-sia"
 },
 "2016847|Medicina de peces": {
  "cod": "2016847",
  "nombre": "Medicina de peces",
  "vigente": true,
  "unidad": null,
  "creditos": 2,
  "semanas": null,
  "horas": null,
  "validable": null,
  "asistencia": null,
  "libreEleccion": null,
  "descripcion": "La producción piscícola de especies de consumo y el uso de peces como biomodelos en investigación, indicadores de contaminación y mascotas (peces ornamentales) han hecho que el conocimiento en la medicina de estas especies sea cada día más necesario para el médico veterinario, zootecnista y profesional de áreas afines. La humanidad ha puesto su mira en la producción acuícola intensiva como una alternativa en la obtención de alimento de alta calidad. Sin embargo, en dichos sistemas productivos las especies son cultivadas en altas densidades de siembra generando factores de riesgo que favorecen el deterioro de la calidad del agua y la proliferación de patógenos . De otra parte, los peces pueden ofrecer características óptimas para ser utilizados como bioindicadores de contaminación acuática y ambiental ya que varios programas de monitoreo ambiental se apoyan en el uso de estas especies para hacer seguimiento a las condiciones de salubridad de los cuerpos de agua. Por ello, el conocimiento de la biología y la medicina de estas especies es igualmente importante para poder interpretar y diagnosticar los cambios generados por la exposición de estos organismos a contaminantes potenciales presentes en la agua. Finalmente, la comercialización de peces como mascotas en el mundo entero exige conocimiento en el control, prevención y tratamiento de enfermedades tanto en sistemas de gran escala abiertos al público (acuarios de exhibición) como en sistemas pequeños en los hogares de los acuariófilos. La Facultad de Medicina Veterinaria y de Zootecnia de la Universidad Nacional de Colombia, sede Bogotá, no ha sido ajena a estos desarrollos y necesidades. Por esta razón se dio la creación años atras de la Línea de Profundización en Acuicultura, la oferta de líneas de investigación en el posgrado en Salud y Producción Animal, asi como la realización periódica de seminarios y congresos de educación continuada en el área.",
  "contenido": null,
  "tipologia": "DISCIPLINAR OPTATIVA",
  "via": "catalogo-sia"
 },
 "2017132|Mercadeo agropecuario": {
  "cod": "2017132",
  "nombre": "Mercadeo agropecuario",
  "vigente": true,
  "unidad": null,
  "creditos": 3,
  "semanas": null,
  "horas": null,
  "validable": null,
  "asistencia": null,
  "libreEleccion": null,
  "descripcion": "En la optativa de mercadeo agropecuario, se pretende dotar al estudiante de competencias analíticas y prácticas con las cuales fundamente y comprenda la forma en que está estructurado el mercadeo de los productos agropecuarios y agroindustriales, dando especial atención al producto que demanda un mercado, como objetivo de la producción, el costo que implica producirlo, al igual que las variables que permiten determinar el precio de mercado, haciéndolo competitivo frente a otros productos homogéneos (commodities) o especializados del sector agropecuario. Así mismo comprender la necesidad de impulsarlo a través de los canales de mercadeo (producción, acopio, mayorista, distribución, consumo) y la forma como la publicidad y los medios de comunicación deben hacer del producto un factor básico para el consumidor.",
  "contenido": null,
  "tipologia": "DISCIPLINAR OPTATIVA",
  "via": "catalogo-sia"
 },
 "2017096|Trabajo de campo Quindío": {
  "cod": "2017096",
  "nombre": "Trabajo de campo Quindío",
  "vigente": true,
  "unidad": null,
  "creditos": 2,
  "semanas": null,
  "horas": null,
  "validable": null,
  "asistencia": null,
  "libreEleccion": null,
  "descripcion": null,
  "contenido": null,
  "tipologia": "DISCIPLINAR OPTATIVA",
  "via": "catalogo-sia"
 },
 "2017095|Trabajo de campo Los Llanos": {
  "cod": "2017095",
  "nombre": "Trabajo de campo Los Llanos",
  "vigente": true,
  "unidad": null,
  "creditos": 2,
  "semanas": null,
  "horas": null,
  "validable": null,
  "asistencia": null,
  "libreEleccion": null,
  "descripcion": null,
  "contenido": null,
  "tipologia": "DISCIPLINAR OPTATIVA",
  "via": "catalogo-sia"
 },
 "2017094|Trabajo de campo Costa Atlántica": {
  "cod": "2017094",
  "nombre": "Trabajo de campo Costa Atlántica",
  "vigente": true,
  "unidad": null,
  "creditos": 2,
  "semanas": null,
  "horas": null,
  "validable": null,
  "asistencia": null,
  "libreEleccion": null,
  "descripcion": null,
  "contenido": null,
  "tipologia": "DISCIPLINAR OPTATIVA",
  "via": "catalogo-sia"
 },
 "2022951|Prácticas integradas reproducción animal": {
  "cod": "2022951",
  "nombre": "Prácticas integradas reproduccion animal",
  "vigente": true,
  "unidad": null,
  "creditos": 20,
  "semanas": null,
  "horas": null,
  "validable": null,
  "asistencia": null,
  "libreEleccion": null,
  "descripcion": null,
  "contenido": null,
  "tipologia": "LIBRE ELECCIÓN",
  "via": "catalogo-sia"
 },
 "2022952|Prácticas integradas medicina aviar y producción avícola": {
  "cod": "2022952",
  "nombre": "Prácticas integradas medicina aviar y produccion avicola",
  "vigente": true,
  "unidad": null,
  "creditos": 20,
  "semanas": null,
  "horas": null,
  "validable": null,
  "asistencia": null,
  "libreEleccion": null,
  "descripcion": "LAS LINEAS DE PROFUNDIZACION CONTENIDAS EN EL PLAN DE ESTUDIOS TIENEN EN CUENTA FUNDAMENTALMENTE LOS POSIBLES CAMPOS DE ACCION DEL PROFESIONAL LOS CUALES ESTAN DEFINIDOS POR LOS OBJETIVOS GENERALES DEL PROGRAMA. - HACIENDO UN RESUMEN DE LOS RECURSOS FISI",
  "contenido": null,
  "tipologia": "LIBRE ELECCIÓN",
  "via": "catalogo-sia"
 },
 "2022953|Prácticas integradas medicina de rumiantes": {
  "cod": "2022953",
  "nombre": "Prácticas integradas medicina de rumiantes",
  "vigente": true,
  "unidad": null,
  "creditos": 20,
  "semanas": null,
  "horas": null,
  "validable": null,
  "asistencia": null,
  "libreEleccion": null,
  "descripcion": null,
  "contenido": null,
  "tipologia": "LIBRE ELECCIÓN",
  "via": "catalogo-sia"
 },
 "2022954|Prácticas integradas en medicina equina": {
  "cod": "2022954",
  "nombre": "Prácticas integradas en medicina equina",
  "vigente": true,
  "unidad": null,
  "creditos": 20,
  "semanas": null,
  "horas": null,
  "validable": null,
  "asistencia": null,
  "libreEleccion": null,
  "descripcion": null,
  "contenido": null,
  "tipologia": "LIBRE ELECCIÓN",
  "via": "catalogo-sia"
 },
 "2022955|Prácticas integradas medicina y cirugía de pequeños animales": {
  "cod": "2022955",
  "nombre": "Prácticas integradas medicina y cirugia de pequeños animales",
  "vigente": true,
  "unidad": null,
  "creditos": 20,
  "semanas": null,
  "horas": null,
  "validable": null,
  "asistencia": null,
  "libreEleccion": null,
  "descripcion": null,
  "contenido": null,
  "tipologia": "LIBRE ELECCIÓN",
  "via": "catalogo-sia"
 },
 "2022956|Prácticas integradas medicina y producción porcina": {
  "cod": "2022956",
  "nombre": "Prácticas integradas medicina y producción porcina",
  "vigente": true,
  "unidad": null,
  "creditos": 20,
  "semanas": null,
  "horas": null,
  "validable": null,
  "asistencia": null,
  "libreEleccion": null,
  "descripcion": null,
  "contenido": null,
  "tipologia": "LIBRE ELECCIÓN",
  "via": "catalogo-sia"
 },
 "2022957|Prácticas integradas salud pública e infectología": {
  "cod": "2022957",
  "nombre": "Prácticas integradas salud pública e infectología",
  "vigente": true,
  "unidad": null,
  "creditos": 20,
  "semanas": null,
  "horas": null,
  "validable": null,
  "asistencia": null,
  "libreEleccion": null,
  "descripcion": "SE ESPERA QUE AL FINALIZAR EL CURSO LAS Y LOS ESTUDIANTES ESTÉN EN CAPACIDAD DE:\n\n1. DEFINIR UNA PREGUNTA DE INVESTIGACIÓN\n2. REALIZAR UN ESTADO DEL ARTE SOBRE EL TEMA SELECCIONADO Y PRESENTARLO EN FORMA DE ARTÍCULO\n3. HACER UNA PRESENTACIÓN ORAL DEL TEMA",
  "contenido": null,
  "tipologia": "LIBRE ELECCIÓN",
  "via": "catalogo-sia"
 },
 "2022958|Prácticas integradas animales silvestres y de laboratorio": {
  "cod": "2022958",
  "nombre": "Prácticas integradas animales silvestres y de laboratorio",
  "vigente": true,
  "unidad": null,
  "creditos": 20,
  "semanas": null,
  "horas": null,
  "validable": null,
  "asistencia": null,
  "libreEleccion": null,
  "descripcion": null,
  "contenido": null,
  "tipologia": "LIBRE ELECCIÓN",
  "via": "catalogo-sia"
 },
 "2026111|Prácticas integradas en patología veterinaria": {
  "cod": "2026111",
  "nombre": "Prácticas integradas en patología veterinaria",
  "vigente": true,
  "unidad": null,
  "creditos": 20,
  "semanas": null,
  "horas": null,
  "validable": null,
  "asistencia": null,
  "libreEleccion": null,
  "descripcion": "Entrenar a los asistentes en el campo de la etiología, patogénesis, descripción de cambios macroscópicos, planteamiento de diagnósticos: morfológicos. resaltar la importancia de la adecuada utilización de los laboratorios diagnósticos para solucionar problemas sanitarios en animales.\nActualizar los conocimientos y experiencia en la descripción de lesiones, formulación de diagnósticos morfológicos concisos y precisos, posibles diagnósticos diferenciales y el etiológico más probable.\nActualizar los conocimientos y experiencia para utilizar la terminología correcta relacionada con los hallazgos macroscópicos de a necropsia.\nActualizar los conocimientos y experiencia para la presentación de informes de patología (necropsia), toma de fotos de lesiones.\nActualizar los conocimientos y experiencia para identificar las patologías más prevalentes en especies nativas y exóticas trabajadas en nuestro país (que muestras se deben enviar y a que laboratorios).",
  "contenido": null,
  "tipologia": "LIBRE ELECCIÓN",
  "via": "catalogo-sia"
 },
 "1000001|Matemáticas Básicas": {
  "cod": "1000001",
  "nombre": "Matemáticas Básicas",
  "vigente": true,
  "unidad": null,
  "creditos": 4,
  "semanas": null,
  "horas": null,
  "validable": null,
  "asistencia": null,
  "libreEleccion": null,
  "descripcion": "OBJETIVOS:\nGenerales\n¿ Brindar al estudiante los fundamentos conceptuales para abordar los cursos posteriores que requieran la matemática básica.\n¿ Promover a través de los talleres, una participación activa del estudiante en su proceso de aprendizaje matemático.\n¿ Generar un espacio y tiempo más adecuados para que el estudiante madure e interiorice los conocimientos adquiridos.\nEspecíficos\n¿ Presentar elementos básicos de lógica que permitan al estudiante incorporar formalismo y validez a sus argumentos.\n¿ Desarrollar habilidades básicas para el manejo de operaciones aritméticas y entre conjuntos\n¿ Lograr un manejo adecuado de las expresiones algebraicas.\n¿ Familiarizar al alumno con la noción de función, su representación gráfica e interpretación, y trabajar con algunas funciones fundamentales tales como las lineales, cuadráticas, exponenciales, logarítmicas y trigonométricas.\n¿ Repasar elementos de la geometría euclidiana básica y de la trigonometría elemental.\n¿ Hacer una introducción a los métodos de conteo.",
  "contenido": null,
  "tipologia": "NIVELACIÓN",
  "via": "catalogo-sia"
 },
 "1000002|Lecto-Escritura": {
  "cod": "1000002",
  "nombre": "Lecto-Escritura",
  "vigente": true,
  "unidad": null,
  "creditos": 4,
  "semanas": null,
  "horas": null,
  "validable": null,
  "asistencia": null,
  "libreEleccion": null,
  "descripcion": "El objetivo de este curso nivelatorio es cualificar la competencia argumentativa de los estudiantes, en lectura y escritura, por medio de la apropiación de estrategias de comprensión y expresión.\nAl finalizar el curso los estudiantes estarán en la capacidad de:\n- Identificar distintos modos discursivos presentes en un texto argumentativo.\n- Identificar la estructura argumentativa de un texto: Tesis central o hipótesis, premisas, red de relaciones entre la premisas.\n- Emitir un juicio de valor en la relación con la estructura identificada.\n- Identificar las distintas posturas que origina la argumentación contenida en el texto.\n- Construir un texto que tenga una estructura argumentativa.",
  "contenido": null,
  "tipologia": "NIVELACIÓN",
  "via": "catalogo-sia"
 }
};
